#!/bin/bash
## restart-unicorn for restart-unicorn in /Users/fresh/nagios/check_unicorn_memory
##
## Made by Anthony Scalisi
## <scalisi.a@gmail.com>
##
## Started on  Wed May 30 13:12:24 2012 Anthony Scalisi
## Last update Wed May 30 13:46:25 2012 Anthony Scalisi
##

hostname=`hostname`

RAILS_ROOT=/home/deploy/www/taskrabbit/current
log_path=/usr/local/nagios/var
PID="$RAILS_ROOT"/tmp/pids/unicorn.pid


case "$1" in
    OK)
	;;
    UNKNOWN)
	;;
    WARNING)
	;;
    CRITICAL)
        case "$2" in
            SOFT)
               	case "$3" in
               	    2)
                      	echo "`date` - Unicorn workers using too much memory, about to reload master, (3rd soft critical state) - SOFT"  >> $log_path/eventhandlers.log
                  	;;
		esac
		;;
	    HARD)
		echo "`date` - Unicorn - Reloading master - HARD"  >> $log_path/eventhandlers.log
		echo "`date` - Unicorn - kill -USR2 `cat "$PID"`" >> $log_path/eventhandlers.log
		echo "`date` - Unicorn - end of the eventhandler"
		;;
	esac
	;;
esac
exit 0
